COPYRIGHT
LICENSE
README.md

Adds the full [CC-BY-SA 4.0 license text](https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt) and clarifies the specific version in use.

Update CC-BY-SA licensing

---

src/ZenKeyboardShortcuts.mjs

Update ZenKeyboardShortcuts.mjs - Add Duplicate Tab shortcut

Update ZenKeyboardShortcuts.mjs - Add Duplicate Tab shortcut

---

src/ZenWorkspaces.mjs

Needed for zen-browser/desktop#604

Edit Workspaces (component updates)

---

src/ZenWorkspaces.mjs

This should fix [this issue](https://github.com/zen-browser/desktop/issues/1196). Also, sorry for the formatter changes (prettier).

Fixing workspace change duplicates

---

src/ZenThemesImporter.mjs

- remove dom elements on enabled = false

refactor(zenThemesImporter): renamed disabled to enabled

---

src/ZenKeyboardShortcuts.mjs

Reverts zen-browser/components#14

Revert "Update ZenKeyboardShortcuts.mjs"

---

src/ZenSidebarManager.mjs

Make the zen sidebar draggable, also made it resizable on all 4 sides. Made sure the sidebar will never leave it's wrapper.

Make zen sidebar draggable

---

src/ZenSidebarManager.mjs

Ensure the back and forward button for web panel are disabled and greyed out when they can't be used.

Disable back and forward button inside web panel when they can't be used.

---

src/ZenViewSplitter.mjs

zen.splitView.change-on-hover currently doesn't do anything. Fix so change on hover only happens when the pref is enabled.

Fix splitView change on hover not listening to pref.

---

src/ZenWorkspaces.mjs
src/ZenWorkspacesStorage.mjs

This PR introduces improvements to workspace ordering and change tracking in the Zen Workspaces system:
- **Workspace Ordering:**
- Introduces a new `updateWorkspaceOrder` method to update workspace positions.
- Reorders workspaces with large increments to avoid frequent reordering, ensuring consistent ordering after changes.
- Implements a mechanism to check for necessary reordering after position updates and reorder all workspaces if required.
- **Changes Tracking:**
- Tracks changes to workspaces by inserting a record in `zen_workspaces_changes` for each modified workspace.
- Adds an index on `uuid` column in `zen_workspaces_changes` table for faster querying.
- Updates `getLastChangeTimestamp` method to return the last change timestamp from the changes tracking table, providing …

Fix(workspaces) performance optimizations

---

src/ZenCompactMode.mjs

Revert logic in ZenCompactMode.mjs, make floating compact mode work with padding.

Fix floating compact mode

---

src/ZenPinnedTabManager.mjs

This PR fixes an issue where middle clicking a pinned tab would not follow the behavior of pinned tab close shortcut.
Also, this PR adds the ability to store the triggering principal for pinned tabs in the session store. This allows us to correctly restore pinned tabs when a user has multiple profiles open, as the triggering principal will be used to determine which profile the pinned tab belongs to.
The following changes were made:
- Added a new attribute, "zen-pinned-triggering-principal", to pinned tabs to store the triggering principal.
- Updated the session store to store and restore the triggering principal for pinned tabs.
- Updated the `ZenPinnedTabManager` to set and get the triggering principal for pinned tabs.
This change is necessary to ensure that pinned tabs are correctly …

Fix: Add middle click listener to pinned tabs to follow the behavior of pinned tab close shortcut

---

src/ZenViewSplitter.mjs

Better placement for Open In Split View

---

src/ZenWorkspaces.mjs

Related to #https://github.com/zen-browser/desktop/issues/2121

Fixing workspaces icon picker

---

src/ZenKeyboardShortcuts.mjs

Recreate shortcuts file if not exist/deleted -  ZenKeyboardShortcuts.mjs
Fix this black screen of death:

Recreate shortcuts file if not exist/deleted -  ZenKeyboardShortcuts.mjs

---

src/ZenWorkspaces.mjs

Added a preference to keep default behavior or apply the new one.
Depends on:
https://github.com/zen-browser/desktop/pull/2251

Fix: Open new tab when last unpinned tab is closed in workspace and no pinned tabs are loaded

---

src/ZenWorkspaces.mjs

This PR adds the ability to move a workspace to the end of the workspace list by dragging it to a designated drop target.
The changes include:
- Creation of a new "last position drop target" element that allows dragging a workspace to the end.
- Event listeners for dragover, dragenter, dragleave, and drop events on the drop target element.
- Implementation of `moveWorkspaceToEnd` function to update the workspace positions in storage when a workspace is moved to the end.
- Reorder mode is exited if the panel is closed.
- Updates to the workspace list to include the last position drop target.
- Reorder mode is automatically disabled when closing the workspaces panel
Depends on:
https://github.com/zen-browser/desktop/pull/2309

Fix: Add functionality to move workspace to the end and disable reorder mode on panel close

---

src/ZenViewSplitter.mjs

Frame and Video/Image Split View

Frame and Video/Image Split View

---

src/ZenTabUnloader.mjs

Reverts zen-browser/components#71

Revert "Added ram check"

---

src/ZenPinnedTabManager.mjs
src/ZenPinnedTabsStorage.mjs
src/ZenWorkspaces.mjs

This PR introduces pinned tab persistence across windows and ability to pin a tab to either a workspace or globally.
- **Pinned Tab Storage:**
- Implements a database-based storage system for pinned tabs using PlacesUtils.
- Provides methods for saving, retrieving, deleting, and managing pinned tabs.
- Tracks changes to pinned tabs for efficient updates.
- **Workspace Integration:**
- Allows pinned tabs to be associated either with specific workspaces or shown across all of them
- Ensures that pinned tabs are not inadvertently moved between workspaces.

Feature: Introduce pinned tab persistence and global/workspace based pinned tabs

---

src/ZenGradientGenerator.mjs

Allows users to spawn color dots directly where they click rather than automatically spawning the dot at white.
https://github.com/user-attachments/assets/d121e7f6-461f-4c10-a903-cb556be107ea

Add the ability to spawn color dots where you click
