zen-browser/components

src/ZenKeyboardShortcuts.mjs
Ctrl+Shift+P is defauft private browsing, change Sidebar shortcut to Alt+P instead.
https://github.com/zen-browser/desktop/issues/516
=> Ctrl+Shift+P is defauft private browsing

src/ZenSidebarManager.mjs
This PR fixes a simple bug where the title of the web panel was not being removed when the panel was unloaded or deleted by the user. Previously, the title would persist even after the panel was no longer in use, leading to potential confusion and UI inconsistency.
=> fix: remove title from web panel on unload

src/ZenWorkspaces.mjs
Implements: zen-browser/desktop#318 and zen-browser/desktop#427
This PR modifies the tab selection behavior when cycling between workspaces. Instead of always selecting the first tab in the current workspace, it keeps track of the last selected tab in each workspace and selects it when the user switches back to that workspace.
Thank you for this browser, been enjoying this feature!
=> feat: Remember the last selected tab when cycling between workspaces

src/ZenWorkspaces.mjs
This change ensures that the `unsafeSaveWorkspaces` function is called asynchronously. This is necessary to prevent blocking the UI thread while saving the workspaces.
=> fix: Await workspace save in `changeWorkspace`

src/ZenThemesCommon.mjs, src/ZenThemesImporter.mjs
- Ability for preferences to have a default value:
- Ability for preferences to have disable the property for multiple OS
- Removed: ![os]:[property] syntax (it is still available for legacy configuration files)
- Internal refactor of zen-settings.js and ZenThemeImporter.mjs so common functionality is now shared through ZenThemesCommon.mjs
=> Zen Mods: New properties config

src/ZenViewSplitter.mjs
Add resizing of views in split view.
Since splitters are inserted in #tabbrowser-tabpanels it may cause some bugs. But so far it seems to work pretty well.
=> Resize views in split view

src/ZenCompactMode.mjs
Compact mode flash hover improvements:
- only retain 'zen-has-hover' when the mouse has left the screen on the side the element is attached (mouse overshoot).
this makes it so that using compact mode still feels very responsive as the popup will immediately close when the mouse is on the screen and not hovering it.
- Use documentElement to detect mouse leaves (for mouse overshoot).
Since hover elements at the edge of the screen, they usually have very small hover boxes it can sometimes happen that the mouse passes over the element without 'mouseleave' firing.
Using documentElement makes it so that the mouse leaving the screen is caught 100% of the time.
I kept a separate option to add hover delays to hover elements.
=> Only flash sidebar when mouse leaves the browser

src/ZenCompactMode.mjs
Always disable sidebar-expand.on-hover if compact mode is is enabled with hide-tabbar to prevent browser being in a state where both are active.
=> Always disable sidebar-expand.on-hover if compact mode is is enabled with hide-tabbar

src/ZenCompactMode.mjs
mouseleave is not 100% accurate, to get the side the mouse left on I bound the x and y value of the mouse by the border of documentElement. This wasn't done properly before.
=> Fix rightside sidebar not always staying open when overshooting mouse.

src/ZenWorkspaces.mjs
Currently, attempting to use any emoji with multiple unicode clusters as a workspace icon results in broken rendering.
Some examples include 👨🏻‍💻 🐦‍⬛ ❤️‍🔥 🐻‍❄️ 👩‍⚕️ 👨🏼‍🦲 ...
This is fixed by using Intl's segmenter module, which is supported starting from Firefox v125.
=> Fix display of ZWJ Emojis as Workspace Icons

src/ZenWorkspaces.mjs, src/ZenWorkspacesStorage.mjs
This PR introduces a new `ZenWorkspacesStorage` class to handle the persistence of workspaces in a database. The previous implementation used JSON files, but this approach brings several advantages, including:
- Improved performance and scalability
- Easier data management and future synchronization implementation
- Enhanced security and data integrity
This change removes the reliance on JSON files and streamlines workspace management, leading to a more robust and reliable system.
Depends on https://github.com/zen-browser/desktop/pull/1870
=> feat(workspaces): Store workspaces in a database

src/ZenWorkspaces.mjs, src/ZenWorkspacesStorage.mjs, src/ZenWorkspacesSync.mjs
This PR adds a new feature to synchronize workspaces to the Services-Sync framework.
- **ZenWorkspacesSync.mjs:** A new file that defines a custom engine for syncing workspaces.
- **ZenWorkspaces.mjs:** Modified to register the ZenWorkspacesEngine with the Service engine manager and to update its state using services-sync's notification system.
This feature enables users to sync their workspaces across devices and seamlessly switch between them using the services-sync mechanism.
Dependent on:
https://github.com/zen-browser/desktop/pull/1899
=> Feature Sync Workspaces to Services-Sync

src/ZenViewSplitter.mjs
Make split view fully customizable by allowing users to drag and drop the windows around.
This pr is a rewrite of original splitview (no longer uses a css grid).
The rewritten version uses a Tree to store the layout of the grid.
Each node stores it's size (percentage) relative to the parent.
Non leaf nodes have at least 2 children and have a direction ('row' or 'column').
Leaf nodes are linked to a tab.
This allows the view to be fully customizable and resize correctly.
Linked desktop pr: https://github.com/zen-browser/desktop/pull/1914
https://github.com/user-attachments/assets/88e8bacc-182d-4632-87f3-23f22f02085d
=> Fully customizable splitview using drag and drop

src/ZenWorkspaces.mjs, src/ZenWorkspacesStorage.mjs
This PR ensures workspaces are migrated after the sync engine is registered so the sync could pick up the newly inserted workspaces.
=> fix(workspaces): Migrate workspaces from JSON to the new storage after sync engine has been registered.

src/ZenKeyboardShortcuts.mjs, src/ZenPinnedTabManager.mjs
This PR introduces a new feature: a pinned tab manager.
- Adds `ZenPinnedTabsObserver` to listen for pinned/unpinned tab events.
- Implements `ZenPinnedTabManager` to handle the logic of managing pinned tabs:
- Stores pinned tab URLs, titles and icons.
- Resets the pinned tab to its saved state when closed.
- Adds a new context menu options to manually reset a pinned tab and to update pinned URL
- Intercepts a shortcut to close a pinned tab to optionally reset its state.
Depends on:
https://github.com/zen-browser/desktop/pull/1957
https://github.com/zen-browser/l10n-packs/pull/66
=> Feature: Add pinned tab url resetting functionality

src/ZenViewSplitter.mjs
Make it impossible for nodes to have the same direction as it's parent when removing a node.
This makes for better resizing: 
https://github.com/user-attachments/assets/52238f9a-a8cf-4b7c-aaec-0ed4955839ae
=> Fix weird resizing after removing tab from split.

src/ZenSidebarManager.mjs
The web panel wrapper switches from position absolute to relative when it's pinned.
This messes up the splitview overlay. Fixed by moving the web panel to the tabbox-wrapper when it's pinned.
=> Fix splitview splitters in wrong position when using web panel (pinned)

src/ZenPinnedTabManager.mjs
This PR fixes an issue where weird stuff would happen if pinned tab didn't have a base url to reset to. If there is no base url, reset tab functionality won't work and it won't be visible in context menu until you click replace pinned url with current or unpin and repin the tab.
=> Fix: Update pinned tab resetting logic

src/ZenWorkspaces.mjs
This PR modifies the `getContextIdIfNeeded` method to automatically use the active workspace context ID for external calls.
Previously, external calls would use the provided `userContextId` if it was different from the active workspace context ID. Now, if `fromExternal` is true and there's an active workspace, the method will return the active workspace context ID, ensuring consistency with the active workspace.
Depends on: https://github.com/zen-browser/desktop/pull/2081
=> Fix: Open external links in workspace's default container

src/ZenWorkspaces.mjs, src/ZenWorkspacesStorage.mjs
This PR introduces the ability to reorder workspaces in the workspaces panel. This adds functionality to move workspaces up and down within the list, allowing users to customize the order in which they appear.
- Added new buttons for moving workspaces up and down.
- Implemented `moveWorkspaceUp` and `moveWorkspaceDown` methods in `ZenWorkspacesStorage` to handle workspace reordering.
- Updated `ZenWorkspaces` to handle the new reorder mode and button events.
- Modified the workspace list UI to display reorder buttons and indicate when reorder mode is active.
Depends on:
https://github.com/zen-browser/l10n-packs/pull/77
https://github.com/zen-browser/desktop/pull/2141
=> Feature:  Workspace reordering

src/ZenCompactMode.mjs
Fixes https://github.com/zen-browser/desktop/issues/941
https://github.com/user-attachments/assets/40867bc1-6c80-4b5c-953e-09c1f68a139d
=> Fixed MacOS window buttons hover in compact mode

src/ZenWorkspaces.mjs
For issue #2237 
Modified the onWorkspaceEditChange method to ensure that the selected attribute is not removed from the button when the same icon is selected. This prevents the icon from being reset to null.
=> Fix issue with workspace icon not updating on edit

src/ZenGradientGenerator.mjs, src/ZenWorkspaces.mjs, src/ZenWorkspacesStorage.mjs, src/ZenWorkspacesSync.mjs
This PR introduces several optimizations to gradient generator and workspaces handling, alongside adding support for syncing of a workspace theme across devices 
The following changes were made:
- Added theme properties to the Zen workspace schema:
- `theme_type` (string): Type of theme (e.g., "gradient", "solid").
- `theme_colors` (JSON string): Array of gradient colors.
- `theme_opacity` (number): Opacity of the theme.
- `theme_rotation` (number): Rotation of the theme.
- `theme_texture` (number): Texture of the theme.
- Updated the `ZenWorkspacesSync` class to handle theme data.
- Added validation for theme properties.
- Updated the `ZenWorkspacesStorage` class to save and load workspace themes.
- Bumped the `ZenWorkspacesEngine` version to 2.
- Updated the color theme on panel close …
=> Fix: Update gradient generator logic and add theme properties to sync engine

src/ZenWorkspaces.mjs
This PR updates the workspace sync logic to notify the theme picker when the active workspace has applied changes from sync.
This ensures that the theme picker can update its state and display the correct theme for the current workspace.
=> Fix: Notify theme picker when workspace has synced

src/ZenEssentialsToolbar.mjs, src/ZenGlanceManager.mjs, src/ZenSidebarManager.mjs, src/ZenWorkspaces.mjs
This PR introduces a new "Essentials" toolbar to the sidebar, providing quick access to frequently used bookmarks.
- The toolbar is based on the `PlacesViewBase` class and uses the `PlacesUtils` API to manage bookmarks.
- It includes a dedicated folder for Zen Essentials bookmarks, ensuring they're organized and easily accessible.
- The toolbar's visibility can be controlled by the `zen.essentials.enabled` preference.
- The toolbar supports drag-and-drop functionality for organizing bookmarks.
- The toolbar items are hidden if they are in another workspace.
- The toolbar supports hover interactions, highlighting the active bookmark on mouseover.
- The toolbar items can be opened in a glance by pressing `Ctrl`, `Alt`, `Shift`, or `Meta` depending on the user's preference.
- The bookmark …
=> Feature: Add Zen Essentials Toolbar

src/ZenPinnedTabManager.mjs
This commit addresses a bug where the `TabClose` event was not being handled correctly by the `ZenPinnedTabManager`. This resulted in incorrect behavior when closing tabs, particularly in the context of multiple windows.
The following changes were made:
- The `TabClose` event is now handled explicitly within the `_onTabEvent` method.
- The `_removePinnedAttributes` method is called to remove any pinned attributes associated with the closed tab.
- The `_onCloseTabShortcut` method is updated to use `e.target?.closest("tab")` to ensure it targets the correct tab element.
This fix ensures that pinned tab attributes are properly removed when a tab is closed, preventing unexpected behavior and data inconsistencies.
=> Fix: Handle TabClose event and middle click in ZenPinnedTabManager
